---
# tasks file for deploy
- name: Ensure OpenJDK and Tomcat9
  apt: name={{item}} state=present
  with_items: 
    - default-jdk
    - tomcat9

- name: Ensure Tomcat is present
  service:
   name: tomcat9
   state: started

- name: Copy war file to production-host
  synchronize:
     src: "{{ java_artefact }}"
     dest: "{{ tomcat_webapp }}"
  delegate_to: build-host
  notify: 
   - restart tomcat9
